[tool.poetry]
package-mode = false

[project]
name = "black-scholes-implied-volatility"
version = "0.1.0"
description = "Options pricing analyzer using the Black-Scholes model with implied volatility, strategy payoff, and live market data via Streamlit"
authors = [
    {name = "Nattawut Boonnoon"}
]
readme = "README.md"
requires-python = "^3.12"
dependencies = [
    "streamlit (>=1.40.0,<2.0.0)",
    "yfinance (==0.2.40)",
    "numpy (>=2.0.0,<3.0.0)",
    "pandas (>=2.2.2,<3.0.0)",
    "plotly (>=5.24.1,<6.0.0)"
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
