[theme]
base = "dark"
primaryColor = "#ca9ee6"
backgroundColor = "#303446"
secondaryBackgroundColor = "#414559"
textColor = "#c6d0f5"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
